### ISSUE TITLE
Renaming repo

### ISSUE THREAD

**Issue by Redecorating** [Redecorating/mbp-16.1-linux-wifi#6]
The kernel this repo has is not just for MBP16,1, so it should be renamed to something like "linux-t2" or "linux-t2-arch". This would make some links dead so I'm not sure if I should do that. Or how to mitigate the impact of changing the repo name (also I have just realised I had issues turned off, I'm not sure when or why I did that, but they are on now).

**Comment by brad** [comment]
> This would make some links dead so I'm not sure if I should do that

@Redecorating I'm pretty sure Github will redirect from the old name indefinitely so I don't think this is an issue

**Comment by Redecorating** [comment]
that's good to know!
